# Generated by Django 4.1 on 2023-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=500)),
                ('Status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Image', models.FileField(upload_to='')),
                ('Designation', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
