# Generated by Django 4.1 on 2023-01-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaymodel',
            name='Complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.complaintmodel'),
        ),
        migrations.AddField(
            model_name='replaymodel',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel'),
        ),
    ]
