# Generated by Django 4.1 on 2023-01-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Time', models.CharField(max_length=255)),
                ('Items', models.CharField(default='', max_length=255)),
                ('Total_Price', models.CharField(default='', max_length=255)),
                ('Payment_Status', models.CharField(default='pending', max_length=255)),
                ('Status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Time', models.CharField(max_length=255)),
                ('Status', models.CharField(default='pending', max_length=255)),
                ('Food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.foodmodel')),
                ('Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.dinningmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Name', models.CharField(max_length=255)),
                ('Card_Number', models.CharField(max_length=255)),
                ('CVC', models.CharField(max_length=255)),
                ('Exp_date', models.CharField(max_length=255)),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.bookmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extra', models.CharField(default='', max_length=25, null=True)),
                ('Date', models.CharField(default='', max_length=255)),
                ('Time', models.CharField(default='', max_length=255)),
                ('Status', models.CharField(default='pending', max_length=255)),
                ('Payment_Status', models.CharField(default='pending', max_length=255)),
                ('Quantity', models.CharField(default='', max_length=50)),
                ('Total_Price', models.CharField(default='', max_length=50)),
                ('Special_Request', models.CharField(default='', max_length=500, null=True)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.foodmodel')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.bookmodel')),
                ('Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.dinningmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Time', models.CharField(max_length=255)),
                ('Feedback', models.CharField(max_length=500)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.foodmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=500)),
                ('Quantity', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('Time', models.CharField(max_length=255)),
                ('Status', models.CharField(default='pending', max_length=255)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.foodmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Time', models.CharField(max_length=255)),
                ('Complaints', models.CharField(max_length=500)),
                ('Status', models.CharField(default='pending', max_length=255)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.foodmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(max_length=255)),
                ('Total_Price', models.CharField(default='', max_length=255)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.foodmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usermodel'),
        ),
    ]
