# Generated by Django 4.1 on 2023-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_deliverymodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='Address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
