# Generated by Django 4.1 on 2023-01-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_deliverymodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='Order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.bookmodel'),
        ),
    ]
