# Generated by Django 4.1 on 2023-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_deliverymodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='Total_Price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
