# Generated by Django 4.1 on 2023-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_deliverymodel_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='Payment_Status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
