# Generated by Django 4.1 on 2023-01-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_deliverymodel_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='Tracking',
            field=models.CharField(default='', max_length=255),
        ),
    ]
