# Generated by Django 4.1 on 2023-01-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DinningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Chair', models.CharField(default='', max_length=255)),
                ('Image', models.FileField(null=True, upload_to='')),
                ('is_active', models.CharField(default='False', max_length=255)),
                ('Booked_Status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Organizer', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food', models.CharField(max_length=255)),
                ('Image', models.FileField(upload_to='')),
                ('Price', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=500)),
                ('Category', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=500)),
                ('Gender', models.CharField(default='', max_length=50)),
                ('DOB', models.CharField(default='', max_length=50)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Image', models.FileField(upload_to='')),
                ('Status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=255)),
                ('Quantity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PresentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=255)),
                ('Attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.attendancemodel')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.staffmodel')),
            ],
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='Manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.managermodel'),
        ),
        migrations.CreateModel(
            name='AbsentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=255)),
                ('Attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.attendancemodel')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.staffmodel')),
            ],
        ),
    ]
